### ISSUE TITLE
Mouse move does not work

### ISSUE THREAD

**Issue by phamhotri** [behzad62/InputEmulator#1]
I try to use mouse example with following command:
MouseEmuTest.exe insert delay 1000 100-100

and it doesn't work, MOUSE don't move :(.

Does we need to adjust x-y coordinate or something else?

**Comment by behzad62** [comment]
Thanks for the report. There was a small bug in the tester tool which I fixed in the released binary. Will update the code soon.

**Comment by behzad62** [comment]
Fixed now.

**Comment by behzad62** [comment]
Fixed now.
